/* ==========================================================================
   NovaStitch Relational Static Mock Database Engine
   40 Unique Premium Items (5 Units per 8 Required Custom Classes)
   ========================================================================== */

const PRODUCTS = [
    // --- HOODIES ---
    {
        id: "hd-01",
        name: "Apex Roar Fleece Over-Hoodie",
        category: "hoodies",
        gender: "men",
        price: 185,
        oldPrice: 240,
        tag: "Bestseller",
        stock: 4,
        description: "Heavyweight 450GSM organic brushed cotton loopback fleece. Boxy relaxed athletic modular silhouette featuring the signature cybernetic digital NovaStitch laser-etched orange roaring tiger emblem front-center.",
        features: ["Heavyweight 450GSM Organic Cotton", "Laser-etched logo detailing", "Pre-shrunk vintage wash treatment"],
        graphicType: "hoodie"
    },
    {
        id: "hd-02",
        name: "Cyber-Stitch Drop Shoulder Cropped Hoodie",
        category: "hoodies",
        gender: "women",
        price: 160,
        oldPrice: null,
        tag: "New Arrival",
        stock: 12,
        description: "Deconstructed raw raw-edge waistband design cropped aesthetic. Features technical high-density rubberized graphic treatments along structural sleeve panel stitch seams.",
        features: ["Exaggerated elongated sleeves", "High-density embossed chest print", "Ribbed knit secure cuffs"],
        graphicType: "hoodie"
    },
    {
        id: "hd-03",
        name: "Vintage Strike Washed Skate Hoodie",
        category: "hoodies",
        gender: "men",
        price: 145,
        oldPrice: 195,
        tag: "Sale",
        stock: 8,
        description: "Acid-washed custom-dyed premium thermal streetwear outer layer with high-impact back puff print detailing celebrating classic athletic sportswear silhouettes.",
        features: ["Vintage ozone pigment wash", "Kangaroo internal secret phone pocket", "Double-lined protective hood"],
        graphicType: "hoodie"
    },
    {
        id: "hd-04",
        name: "Zenith Asymmetrical Wrap Hoodie",
        category: "hoodies",
        gender: "women",
        price: 175,
        oldPrice: null,
        tag: "Limited Run",
        stock: 3,
        description: "High-fashion crossover modular funnel hood construction built for techwear aesthetic layering configurations during colder microclimates.",
        features: ["Crossover magnetic high collar", "Water-resistant performance jersey fleece", "Invisible side zippered pockets"],
        graphicType: "hoodie"
    },
    {
        id: "hd-05",
        name: "Retro Strike Block Oversized Hoodie",
        category: "hoodies",
        gender: "unisex",
        price: 155,
        oldPrice: null,
        tag: "",
        stock: 15,
        description: "Bold triple tone color-blocked configuration paying stylistic homage to German and American 90s archive running club wear.",
        features: ["Relaxed drop-shoulder comfort build", "Premium chenille embroidered tiger patch", "Interlocking safety stitch seams"],
        graphicType: "hoodie"
    },

    // --- T-SHIRTS ---
    {
        id: "ts-01",
        name: "Striated Matrix Graphic Tee",
        category: "t-shirts",
        gender: "men",
        price: 75,
        oldPrice: 95,
        tag: "Sale",
        stock: 22,
        description: "Premium interlocking long-staple luxury combed cotton fabrication featuring vector schematic typography layout on back.",
        features: ["280GSM Luxury Combed Cotton", "High-fidelity silk screen print", "Thick structural mock neck collar line"],
        graphicType: "shirt"
    },
    {
        id: "ts-02",
        name: "Minimalist Script Boyfriend Tee",
        category: "t-shirts",
        gender: "women",
        price: 65,
        oldPrice: null,
        tag: "Core Line",
        stock: 19,
        description: "Ultra soft, breathable daily driver basic layout featuring signature micro tiger crest typography branding hit left chest.",
        features: ["Lightweight slub cotton matrix texture", "Dropped seamless shoulders", "Eco-friendly non-toxic liquid dye processing"],
        graphicType: "shirt"
    },
    {
        id: "ts-03",
        name: "Warped Paradigm Acid Tee",
        category: "t-shirts",
        gender: "men",
        price: 85,
        oldPrice: null,
        tag: "Hot Drop",
        stock: 5,
        description: "Distressed edge detailing vintage oil-wash streetwear tee with screenprinted expanding multi-layered optical illusion typography artwork.",
        features: ["Hand-distressed neck collar and hemline", "Discharge ink breathable printing process", "Custom collection serialization numbering"],
        graphicType: "shirt"
    },
    {
        id: "ts-04",
        name: "Linear Form Ribbed Micro Crop Tee",
        category: "t-shirts",
        gender: "women",
        price: 55,
        oldPrice: 70,
        tag: "Sale",
        stock: 14,
        description: "Form-fitting, flexible rib-knit dynamic modern streetwear styling essential, accented with miniature glowing tiger logo stamp.",
        features: ["Highly elastic premium blend construction", "Contrast flatlock accent stitching lines", "Moisture wicking cool dry performance"],
        graphicType: "shirt"
    },
    {
        id: "ts-05",
        name: "Monochrome Archive Graphic Box Tee",
        category: "t-shirts",
        gender: "unisex",
        price: 80,
        oldPrice: null,
        tag: "",
        stock: 30,
        description: "Square aesthetic wide build silhouette with monochromatic luxury high-density silicone transfer graphic detailing.",
        features: ["Heavy tight-weave interlocked jersey", "Silicone rubber non-fading center patch", "Enzyme washed for maximum skin comfort"],
        graphicType: "shirt"
    },

    // --- CARGO PANTS ---
    {
        id: "cg-01",
        name: "Tactical Recon Modular Cargo Pants",
        category: "cargo pants",
        gender: "men",
        price: 210,
        oldPrice: null,
        tag: "Must Have",
        stock: 6,
        description: "Military-grade ripstop tactical trousers featuring articulated ergonomic multi-panel knee reinforcement systems and modular storage pockets.",
        features: ["Waterproofing DWR surface coating", "8-pocket dual utility geometric configuration", "Ankle bungee cord width regulators"],
        graphicType: "pants"
    },
    {
        id: "cg-02",
        name: "Cyberpunk High-Waist Parachute Cargo",
        category: "cargo pants",
        gender: "women",
        price: 195,
        oldPrice: 250,
        tag: "Trending",
        stock: 7,
        description: "Exaggerated high-volume ultra-lightweight techwear utility balloon trousers featuring signature contrasting tiger-orange nylon hanging security straps.",
        features: ["Ultra-wide volume balloon draping", "Adjustable integrated woven belt loop system", "Breathable tech-nylon construction material"],
        graphicType: "pants"
    },
    {
        id: "cg-03",
        name: "Standard Issue Heavy Canvas Cargo",
        category: "cargo pants",
        gender: "men",
        price: 180,
        oldPrice: null,
        tag: "",
        stock: 11,
        description: "Heavy rugged duck canvas structural skate/workwear trousers with expandable reinforced bellows utility side cargo spacing pockets.",
        features: ["14oz Heavy Duty Duck Cotton Canvas", "Triple-needle structural main seam construction", "Reinforced back hammer loop utility belt"],
        graphicType: "pants"
    },
    {
        id: "cg-04",
        name: "Slit-Ankle Sleek Tailored Cargo Trousers",
        category: "cargo pants",
        gender: "women",
        price: 190,
        oldPrice: null,
        tag: "New",
        stock: 9,
        description: "A hybrid fusion of tailored eveningwear and structural utilitarian streetwear, featuring dynamic lower-leg zipper venting options.",
        features: ["Premium stretch gabardine weave composition", "Hidden invisible zip side security pockets", "Ankle vent premium YKK luxury zippers"],
        graphicType: "pants"
    },
    {
        id: "cg-05",
        name: "Urban Explorer Daily Cargo Jogger",
        category: "cargo pants",
        gender: "unisex",
        price: 165,
        oldPrice: 210,
        tag: "Sale",
        stock: 2,
        description: "Comfort-focused premium flexible stretch-twill multi-purpose streetwear utility joggers with secure zippered cargo bays.",
        features: ["Elasticized comfort waist layout with pull drawcords", "Slim-tapered structural fit lines", "Embroidered tonal branding micro badges"],
        graphicType: "pants"
    },

    // --- BAGS ---
    {
        id: "bg-01",
        name: "Overload Cordura Tech Backpack",
        category: "bags",
        gender: "unisex",
        price: 240,
        oldPrice: 310,
        tag: "Premium",
        stock: 4,
        description: "Indestructible 1000D ballistic Cordura laptop carrier modular transport chassis with customized multi-point laser MOLLE mounting webs.",
        features: ["1000D Genuine Ballistic Cordura Shell", "Fleece-lined suspended 16-inch laptop pocket", "Fidlock German magnetic V-buckle closure"],
        graphicType: "bag"
    },
    {
        id: "bg-02",
        name: "Hyper-Strap Waterproof Messenger Sling",
        category: "bags",
        gender: "unisex",
        price: 135,
        oldPrice: null,
        tag: "Bestseller",
        stock: 18,
        description: "Crossbody fast-access urban exploration courier kit featuring seam-sealed vinyl lining interiors for full weather protection.",
        features: ["Fully waterproof TPU-laminated exterior", "Quick-release quick thumb adjust stabilizer strap", "Dual tactical outer D-Ring anchors"],
        graphicType: "bag"
    },
    {
        id: "bg-03",
        name: "Micro Cyber-Chest Rig Utility Harness",
        category: "bags",
        gender: "unisex",
        price: 115,
        oldPrice: null,
        tag: "Street Icon",
        stock: 6,
        description: "Iconic high-fashion technical utility chest mount loadouts inspired by modern subculture military runway trends.",
        features: ["Breathable air-mesh back ventilation frame", "Dual independent zipper core structural modules", "Reflective safety high-visibility branding hits"],
        graphicType: "bag"
    },
    {
        id: "bg-04",
        name: "Apex Luxury Quilted Tote Carrier",
        category: "bags",
        gender: "women",
        price: 160,
        oldPrice: 200,
        tag: "Sale",
        stock: 8,
        description: "Oversized down-filled insulated buffer nylon tote configuration showcasing the iconic repeating embroidered tiger insignia array patterns.",
        features: ["Padded structural shoulder carry straps", "Inner secure zippered valuables security pocket", "Magnetic main opening quick-seal snaps"],
        graphicType: "bag"
    },
    {
        id: "bg-05",
        name: "Nomad Canvas Expedition Duffle Pack",
        category: "bags",
        gender: "unisex",
        price: 275,
        oldPrice: null,
        tag: "Limited Drop",
        stock: 3,
        description: "High-capacity convertible weekender travel duffle architecture that quickly transforms into fully functional shoulder backpack rigs.",
        features: ["Heavy wax treated water-repellent canvas", "Dedicated isolated ventilated shoe clean compartment", "Heavy-gauge reinforced industrial metal hardware"],
        graphicType: "bag"
    },

    // --- HATS ---
    {
        id: "ht-01",
        name: "Vandal Distressed Dad Cap",
        category: "hats",
        gender: "unisex",
        price: 45,
        oldPrice: null,
        tag: "Essential",
        stock: 40,
        description: "Low-profile unstructured vintage cotton twill curve-brim headwear complete with hand-frayed details and internal moisture headbands.",
        features: ["100% Premium Washed Cotton Twill Base", "Aged brass slider adjustment backstrap", "High density luxury 3D embroidered logo artwork"],
        graphicType: "hat"
    },
    {
        id: "ht-02",
        name: "Matrix Knit Heavy Gauge Beanie",
        category: "hats",
        gender: "unisex",
        price: 40,
        oldPrice: 55,
        tag: "Winter Core",
        stock: 25,
        description: "Four-seam construction thick tight-ribbed fisherman styling beanie configuration deploying premium insulation technologies.",
        features: ["Thermal-regulating advanced acrylic blend", "Wide fold-over protective perimeter cuff design", "Woven double-sided identity exterior tag label"],
        graphicType: "hat"
    },
    {
        id: "ht-03",
        name: "Sector Tech-Nylon Performance Bucket Hat",
        category: "hats",
        gender: "unisex",
        price: 55,
        oldPrice: null,
        tag: "New",
        stock: 12,
        description: "Wide-brim tactical sun protection hat built from ultralight dynamic stretch water-shedding performance nylon weaves.",
        features: ["Laser-cut side ventilation cooling eyelets", "Removable toggle-lock chin cord string safety", "Internal quick-wicking sweatband liner loop"],
        graphicType: "hat"
    },
    {
        id: "ht-04",
        name: "Pro-Form Retro 5-Panel Camp Hat",
        category: "hats",
        gender: "unisex",
        price: 50,
        oldPrice: null,
        tag: "",
        stock: 19,
        description: "Flat-brim square structure camp aesthetic profile modeled after European and East Coast bicycle messenger setups.",
        features: ["Flexible weight-saving soft brim memory core", "Quick-snap webbing clip rear fastener strap", "Subtle side-panel dual breathing screens"],
        graphicType: "hat"
    },
    {
        id: "ht-05",
        name: "Apex Structured Pro Snapback",
        category: "hats",
        gender: "men",
        price: 60,
        oldPrice: 75,
        tag: "Sale",
        stock: 8,
        description: "High-crown stiff front panel wool athletic classic snapback profile presenting the premium roaring tiger graphic badge proudly.",
        features: ["Premium structural wool-blend buckram crown", "Contrasting undersurface grey brim retro finish", "Adjustable secure standard snap fit closure grid"],
        graphicType: "hat"
    },

    // --- DENIM JACKETS ---
    {
        id: "dn-01",
        name: "14oz Selvedge Type-III Trucker Jacket",
        category: "denim jackets",
        gender: "men",
        price: 295,
        oldPrice: 380,
        tag: "Grail",
        stock: 3,
        description: "Raw Japanese selvedge denim vintage Type-III structure featuring custom customized heavy-duty tiger branded metal donut buttons.",
        features: ["14.5oz Raw Indigo Japanese Selvedge Denim", "Intricate tiger-stripe interior custom yoke stitch", "Dual side hidden structural welt slit pockets"],
        graphicType: "jacket"
    },
    {
        id: "dn-02",
        name: "Oversized Distressed Cyber Punk Denim Coat",
        category: "denim jackets",
        gender: "women",
        price: 260,
        oldPrice: null,
        tag: "Statement Piece",
        stock: 5,
        description: "Bleach-washed light indigo modern streetwear drape jacket with massive detailed tiger face line-art laser engraving across the entire back panel.",
        features: ["Exaggerated drop-shoulder boyfriend silhouette", "Heavy localized distressing and frayed hems", "Premium laser etching non-fading art design"],
        graphicType: "jacket"
    },
    {
        id: "dn-03",
        name: "Asphalt Black Coated Moto Denim Outerwear",
        category: "denim jackets",
        gender: "men",
        price: 280,
        oldPrice: null,
        tag: "Restocked",
        stock: 7,
        description: "Wax-treated matte black industrial style denim jacket framework built with unique zippered expandable side seam vents.",
        features: ["Water-resistant protective matte wax coating finish", "Heavy gauge asymmetric gunmetal front zipper lock", "Ribbed moto accordion sleeve movement joints"],
        graphicType: "jacket"
    },
    {
        id: "dn-04",
        name: "Deconstructed Paneled Hybrid Denim Jacket",
        category: "denim jackets",
        gender: "women",
        price: 275,
        oldPrice: 350,
        tag: "Sale",
        stock: 4,
        description: "Avant-garde combination of raw indigo denim fragments interlaced with heavyweight black French loopback cotton terry panels.",
        features: ["Intricate split-media body construction", "Adjustable waist button button strap hardware stabilizers", "Raw unfinished edge border stitching layout design"],
        graphicType: "jacket"
    },
    {
        id: "dn-05",
        name: "Retro Utility Sherpa-Lined Denim Trucker",
        category: "denim jackets",
        gender: "unisex",
        price: 245,
        oldPrice: null,
        tag: "",
        stock: 10,
        description: "Warm cold-weather streetwear staple fully lined with plush faux-sherpa insulation, featuring premium heavy vintage stone wash character.",
        features: ["High-pile insulating interior core sherpa layer", "Sleeve insulation satin quilted lining tracks", "Heavy-duty double button flap chest storage units"],
        graphicType: "jacket"
    },

    // --- SOCKS ---
    {
        id: "sk-01",
        name: "Linear Stripe Impact Crew Socks (3-Pack)",
        category: "socks",
        gender: "unisex",
        price: 35,
        oldPrice: null,
        tag: "Daily Essential",
        stock: 50,
        description: "High-cushion athletic streetwear socks with reinforced arch compression bands and high-density jacquard knit tiger icons.",
        features: ["80% Premium Combed Long-Staple Cotton Base", "Terry loop thick impact zone under-foot cushioning", "Stay-up elastic ribbed performance leg compression"],
        graphicType: "socks"
    },
    {
        id: "sk-02",
        name: "Cyber Neon Quarter-Ankle Fit (2-Pack)",
        category: "socks",
        gender: "unisex",
        price: 28,
        oldPrice: 38,
        tag: "Sale",
        stock: 35,
        description: "Lower profile ventilation activewear socks presenting glowing high-visibility tiger orange accents and heel guards.",
        features: ["CoolMesh top-of-foot custom heat venting tracks", "Seamless toe closure links preventing blistering", "Reflective safety collar rear loop pull tabs"],
        graphicType: "socks"
    },
    {
        id: "sk-03",
        name: "Tie-Dye Cloud Element Crew Sock",
        category: "socks",
        gender: "unisex",
        price: 22,
        oldPrice: null,
        tag: "Trending",
        stock: 42,
        description: "Individually hand-dipped custom pastel pattern streetwear sock base making every single set completely unique.",
        features: ["Hand-processed unique custom dip dye coloration", "Silky soft modal structural microfiber enhanced core", "Reinforced heel capsule shielding structures"],
        graphicType: "socks"
    },
    {
        id: "sk-04",
        name: "Ribbed Luxury Cashmere Blend Sleep Sock",
        category: "socks",
        gender: "women",
        price: 48,
        oldPrice: null,
        tag: "Premium Cozy",
        stock: 15,
        description: "Ultra-luxurious premium loungewear streetwear crossover sock option knit carefully out of fine Mongolian cashmere yarns.",
        features: ["30% Real Mongolian Cashmere natural fibers", "Non-binding loose-fit comfort ribbing perimeter", "Micro suede non-slip bottom graphic typography footprints"],
        graphicType: "socks"
    },
    {
        id: "sk-05",
        name: "Retro Athletic Stripe Knee-High Tube",
        category: "socks",
        gender: "unisex",
        price: 25,
        oldPrice: 32,
        tag: "Retro Pack",
        stock: 28,
        description: "Old-school skating subculture inspired high rise knee socks sporting classic vintage sports stripe configurations.",
        features: ["Durable elastic-core cotton composite build", "Extra long length versatile scrunched layout styling", "Embroidered high relief luxury branding crests"],
        graphicType: "socks"
    },

    // --- SNEAKERS ---
    {
        id: "sn-01",
        name: "Quantum Roar Platform Chunky Runner",
        category: "sneakers",
        gender: "unisex",
        price: 320,
        oldPrice: 420,
        tag: "Grail Footwear",
        stock: 2,
        description: "Inspired by high-fashion runway chunky sneakers and technical performance trail shoes. Deploys advanced EVA foam platform shock absorption cells.",
        features: ["Italian full grain calfskin leather panels", "Futuristic sculpted custom dual density EVA midsole", "Speed-lacing quick cable toggle fastener routing"],
        graphicType: "sneaker"
    },
    {
        id: "sn-02",
        name: "Velocty-X knit Futuristic Minimalist Low",
        category: "sneakers",
        gender: "men",
        price: 260,
        oldPrice: null,
        tag: "Hot Drop",
        stock: 6,
        description: "One-piece digital breathable master-knit upper chassis that maps seamlessly to the dynamic anatomical contours of your foot.",
        features: ["Engineered highly elastic breathable master-knit shell", "Ultralight non-slip carbon rubber outsole plate", "Responsive energy returning step capsule cells"],
        graphicType: "sneaker"
    },
    {
        id: "sn-03",
        name: "Terra-Strike High-Top Vulcanized Skate Shoe",
        category: "sneakers",
        gender: "unisex",
        price: 185,
        oldPrice: null,
        tag: "Core Heritage",
        stock: 14,
        description: "Rugged durable heavyweight canvas traditional flat sole skateboard sneaker frame showing heavy wrap-around side bumper graphics.",
        features: ["16oz ballistic canvas weave structural sidewalls", "Double-vulcanized protective rubber sidewall tapes", "High-grip industrial custom waffle tread layout"],
        graphicType: "sneaker"
    },
    {
        id: "sn-04",
        name: "Stratus Luxe Premium Leather Court Mid",
        category: "sneakers",
        gender: "women",
        price: 290,
        oldPrice: 360,
        tag: "Limited Stock",
        stock: 3,
        description: "Premium retro basketball aesthetics re-imagined with ultra clean monochrome architectural profiles and luxury metallic gold tiger lace dubraes.",
        features: ["Pebbled drum-dyed luxury leather construction", "Perforated breathability micro array toe box zones", "Metallic luxury gold-plated steel accent hardware closures"],
        graphicType: "sneaker"
    },
    {
        id: "sn-05",
        name: "Element-Y Modular Tech-Wear Sandal Shoe",
        category: "sneakers",
        gender: "unisex",
        price: 210,
        oldPrice: null,
        tag: "Concept",
        stock: 8,
        description: "A hybrid neoprene sock slip-on sneaker variant utilizing outer hard exoskeleton cages and tactical quick adjustment straps.",
        features: ["Flexible moisture-resistant neoprene inner booties", "Indestructible hard polymer composite outer clip exoskeletons", "Quick release high load-bearing side buckle pins"],
        graphicType: "sneaker"
    }
];

// Globally Expose Module Data context if running in standard browser setups
window.PRODUCTS_DB = PRODUCTS;