/* =========================================================
   FruitStitch Product Database
   ========================================================= */

window.PRODUCTS_DB = [
    {
        id: 1,
        name: "Dragonfruit Cyber Hoodie",
        category: "hoodies",
        gender: "men",
        price: 185,
        oldPrice: 240,
        tag: "BESTSELLER",
        image: "images/dragonfruit-hoodie.png",
        emoji: "🐉",
        accent: "#ff2a6d",
        description: "A bold dragonfruit-inspired hoodie with soft fleece, oversized fit, and premium streetwear energy.",
        stock: 8,
        rating: 4.9,
        reviews: 128,
        features: ["Premium cotton fleece", "Oversized fit", "Embroidered FruitStitch logo", "Soft inner lining"]
    },
    {
        id: 2,
        name: "Kiwi Drop Shoulder Hoodie",
        category: "hoodies",
        gender: "women",
        price: 160,
        tag: "NEW",
        image: "images/kiwi-hoodie.png",
        emoji: "🥝",
        accent: "#00ff88",
        description: "Electric kiwi green hoodie made for bright outfits and comfortable everyday wear.",
        stock: 12,
        rating: 4.8,
        reviews: 94,
        features: ["Drop shoulder design", "Breathable fabric", "Relaxed fit", "Neon fruit tone"]
    },
    {
        id: 3,
        name: "Blueberry Skate Hoodie",
        category: "hoodies",
        gender: "men",
        price: 145,
        oldPrice: 195,
        tag: "SALE",
        image: "images/blueberry-hoodie.png",
        emoji: "🫐",
        accent: "#00e5ff",
        description: "A washed blueberry hoodie with a skate-ready look and soft premium finish.",
        stock: 5,
        rating: 4.7,
        reviews: 76,
        features: ["Vintage wash", "Durable stitching", "Skate-inspired fit", "Soft fleece interior"]
    },
    {
        id: 4,
        name: "Mango Cropped Hoodie",
        category: "hoodies",
        gender: "women",
        price: 175,
        tag: "LIMITED",
        image: "images/mango-crop-hoodie.png",
        emoji: "🥭",
        accent: "#ffa500",
        description: "A bright mango cropped hoodie with a modern streetwear silhouette.",
        stock: 3,
        rating: 4.9,
        reviews: 62,
        features: ["Cropped cut", "Limited edition", "Premium ribbed cuffs", "Bold mango colorway"]
    },
    {
        id: 5,
        name: "Strawberry Basics Tee",
        category: "t-shirts",
        gender: "unisex",
        price: 45,
        tag: "BASIC",
        image: "images/strawberry-tee.png",
        emoji: "🍓",
        accent: "#ff4d6d",
        description: "A clean strawberry-red everyday tee with a soft cotton feel.",
        stock: 20,
        rating: 4.6,
        reviews: 148,
        features: ["100% cotton", "Everyday fit", "Soft touch fabric", "Minimal logo print"]
    },
    {
        id: 6,
        name: "Passion Fruit Graphic Tee",
        category: "t-shirts",
        gender: "men",
        price: 55,
        tag: "GRAPHIC",
        image: "images/passion-fruit-tee.png",
        emoji: "🍇",
        accent: "#a855f7",
        description: "A bold graphic tee inspired by passion fruit colors and street art.",
        stock: 15,
        rating: 4.7,
        reviews: 81,
        features: ["Premium graphic print", "Soft jersey cotton", "Relaxed fit", "Streetwear design"]
    },
    {
        id: 7,
        name: "Pineapple Oversized Tee",
        category: "t-shirts",
        gender: "women",
        price: 52,
        tag: "TRENDING",
        image: "images/pineapple-tee.png",
        emoji: "🍍",
        accent: "#ffcc00",
        description: "A tropical oversized tee with bright pineapple energy.",
        stock: 18,
        rating: 4.8,
        reviews: 73,
        features: ["Oversized fit", "Tropical graphic", "Lightweight cotton", "Summer-ready design"]
    },
    {
        id: 8,
        name: "Avocado Utility Cargo Pants",
        category: "cargo pants",
        gender: "men",
        price: 125,
        tag: "UTILITY",
        image: "images/avocado-cargo.png",
        emoji: "🥑",
        accent: "#6ba82f",
        description: "Deep avocado green cargos with utility pockets and a clean tapered fit.",
        stock: 9,
        rating: 4.8,
        reviews: 59,
        features: ["Multiple pockets", "Adjustable waistband", "Durable fabric", "Tapered streetwear fit"]
    },
    {
        id: 9,
        name: "Cherry High-Waist Cargo",
        category: "cargo pants",
        gender: "women",
        price: 135,
        tag: "STYLE",
        image: "images/cherry-cargo.png",
        emoji: "🍒",
        accent: "#dc143c",
        description: "A black high-waist cargo with cherry accent details.",
        stock: 7,
        rating: 4.7,
        reviews: 66,
        features: ["High-waist cut", "Cherry details", "Comfort stretch", "Premium cargo build"]
    },
    {
        id: 10,
        name: "Watermelon Court Sneaker",
        category: "sneakers",
        gender: "unisex",
        price: 155,
        tag: "FRESH",
        image: "images/watermelon-sneaker.png",
        emoji: "🍉",
        accent: "#ff3366",
        description: "A vibrant watermelon-inspired sneaker made for comfort and style.",
        stock: 11,
        rating: 4.9,
        reviews: 102,
        features: ["Cushioned sole", "Breathable upper", "Court-inspired shape", "FruitStitch side logo"]
    },
    {
        id: 11,
        name: "Blueberry High-Top Skate",
        category: "sneakers",
        gender: "men",
        price: 165,
        tag: "SKATE",
        image: "images/blueberry-sneaker.png",
        emoji: "🫐",
        accent: "#4169e1",
        description: "Electric blueberry high-top sneakers built for skate and street outfits.",
        stock: 6,
        rating: 4.8,
        reviews: 88,
        features: ["High-top support", "Grip sole", "Durable toe cap", "Skate-ready comfort"]
    },
    {
        id: 12,
        name: "Orange Crossbody Bag",
        category: "bags",
        gender: "unisex",
        price: 95,
        tag: "ACCESSORY",
        image: "images/orange-crossbody.png",
        emoji: "🍊",
        accent: "#ff8c00",
        description: "A fresh orange crossbody bag with clean compartments and a premium strap.",
        stock: 14,
        rating: 4.6,
        reviews: 47,
        features: ["Adjustable strap", "Multiple pockets", "Water-resistant shell", "Compact carry"]
    },
    {
        id: 13,
        name: "Grape Backpack Pro",
        category: "bags",
        gender: "unisex",
        price: 125,
        tag: "PRO",
        image: "images/grape-backpack.png",
        emoji: "🍇",
        accent: "#7c3aed",
        description: "A deep grape backpack designed for school, work, and everyday carry.",
        stock: 10,
        rating: 4.8,
        reviews: 55,
        features: ["Laptop sleeve", "Padded back", "Large storage", "Premium zippers"]
    },
    {
        id: 14,
        name: "Lemon Dad Cap",
        category: "hats",
        gender: "unisex",
        price: 35,
        tag: "CLASSIC",
        image: "images/lemon-cap.png",
        emoji: "🍋",
        accent: "#ffff00",
        description: "A bright lemon-yellow dad cap with a clean embroidered logo.",
        stock: 25,
        rating: 4.5,
        reviews: 91,
        features: ["Adjustable strap", "Embroidered logo", "Cotton twill", "Classic shape"]
    },
    {
        id: 15,
        name: "Lime Green Beanie",
        category: "hats",
        gender: "unisex",
        price: 38,
        tag: "WINTER",
        image: "images/lime-beanie.png",
        emoji: "🍈",
        accent: "#00ff00",
        description: "A lime green knit beanie made for cold weather and bold outfits.",
        stock: 16,
        rating: 4.6,
        reviews: 44,
        features: ["Warm knit", "Stretch fit", "Soft fabric", "Bright lime color"]
    },
    {
        id: 16,
        name: "Pomegranate Denim Jacket",
        category: "denim jackets",
        gender: "men",
        price: 145,
        tag: "CLASSIC",
        image: "images/pomegranate-denim.png",
        emoji: "❤️",
        accent: "#c41e3a",
        description: "A deep pomegranate-tinted denim jacket with a timeless streetwear cut.",
        stock: 8,
        rating: 4.7,
        reviews: 68,
        features: ["Premium denim", "Classic collar", "Button front", "Durable construction"]
    },
    {
        id: 17,
        name: "Tangerine Cropped Denim",
        category: "denim jackets",
        gender: "women",
        price: 135,
        tag: "TRENDY",
        image: "images/tangerine-denim.png",
        emoji: "🍊",
        accent: "#ff9800",
        description: "A cropped tangerine denim jacket with a bright fashion-forward finish.",
        stock: 7,
        rating: 4.8,
        reviews: 52,
        features: ["Cropped length", "Premium denim", "Bold tangerine wash", "Modern fit"]
    },
    {
        id: 18,
        name: "Berry Mix Crew Socks",
        category: "socks",
        gender: "unisex",
        price: 28,
        tag: "3-PACK",
        image: "images/berry-socks.png",
        emoji: "🫐",
        accent: "#8b4789",
        description: "A colorful berry mix crew sock pack with three fresh designs.",
        stock: 30,
        rating: 4.6,
        reviews: 113,
        features: ["3-pack", "Soft cotton blend", "Crew length", "Colorful fruit patterns"]
    },
    {
        id: 19,
        name: "Peach Dream Ankle Socks",
        category: "socks",
        gender: "women",
        price: 26,
        tag: "CASUAL",
        image: "images/peach-socks.png",
        emoji: "🍑",
        accent: "#ffb6c1",
        description: "Soft peach ankle socks made for comfort and everyday wear.",
        stock: 22,
        rating: 4.5,
        reviews: 39,
        features: ["Ankle length", "Breathable knit", "Soft peach color", "Everyday comfort"]
    }
];

console.log("FruitStitch products loaded:", window.PRODUCTS_DB.length);